services:

  user-service:
    image: kora-user-service:latest
    container_name: kora-user-service
    env_file:
      - ./services/user-service/.env
    ports:
      - "5001:5001"
    restart: unless-stopped

  property-service:
    image: kora-property-service:latest
    container_name: kora-property-service
    env_file:
      - ./services/property-service/.env
    ports:
      - "5002:5002"
    restart: unless-stopped

  rental-service:
    image: kora-rental-service:latest
    container_name: kora-rental-service
    env_file:
      - ./services/rental-service/.env
    ports:
      - "5003:5003"
    restart: unless-stopped

  api-gateway:
    image: kora-api-gateway:latest
    container_name: kora-api-gateway

    environment:
      PORT: 5000
      USER_SERVICE_URL: http://user-service:5001
      PROPERTY_SERVICE_URL: http://property-service:5002
      RENTAL_SERVICE_URL: http://rental-service:5003

    ports:
      - "5000:5000"

    depends_on:
      - user-service
      - property-service
      - rental-service

    restart: unless-stopped

  frontend:
    image: kora-frontend:latest
    container_name: kora-frontend

    ports:
      - "5173:5173"

    depends_on:
      - api-gateway

    restart: unless-stopped